from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class MoodInput:
    """
    User's raw mood input from the chatbox.
    """
    text: str


@dataclass
class Recommendation:
    """
    Structured recommendation generated by GPT.

    mood_summary: short summary of the user's emotion
    response_text: supportive text shown to the user
    search_keywords: keywords used to search Spotify
    genres: optional music genre suggestions
    artists: optional artist suggestions
    """
    mood_summary: str
    response_text: str
    search_keywords: List[str] = field(default_factory=list)
    genres: List[str] = field(default_factory=list)
    artists: List[str] = field(default_factory=list)


@dataclass
class Track:
    """
    One track returned from Spotify search.
    """
    title: str
    artist: str
    spotify_url: str
    album: Optional[str] = None
    preview_url: Optional[str] = None
    image_url: Optional[str] = None

    @property
    def embed_url(self) -> str:
        """
        Convert a normal Spotify track URL into an embeddable URL.
        Example:
        https://open.spotify.com/track/abc123
        ->
        https://open.spotify.com/embed/track/abc123
        """
        if "open.spotify.com/track/" in self.spotify_url:
            return self.spotify_url.replace(
                "https://open.spotify.com/track/",
                "https://open.spotify.com/embed/track/"
            ).split("?")[0]
        return self.spotify_url


@dataclass
class MusicTherapyResult:
    """
    Final result returned by the backend.
    """
    mood_input: MoodInput
    recommendation: Recommendation
    tracks: List[Track] = field(default_factory=list)